name: Ingest Smoke (DB status)
on: { workflow_dispatch: {} }

jobs:
  smoke:
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: packages/ingest } }
    env:
      SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
      SSL_CA_PEM: ${{ secrets.SSL_CA_PEM }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '22.x' }
        
      - name: Show resolved env
        shell: bash
        run: |
          echo "PG_SNI_HOST=$PG_SNI_HOST"
          echo "PG_HOST_OVERRIDE=$PG_HOST_OVERRIDE"
          echo "NODE_EXTRA_CA_CERTS=$NODE_EXTRA_CA_CERTS"
          echo "SSL_CA_PEM_PATH=$SSL_CA_PEM_PATH"
          
      - name: DNS check
        run: |
          nslookup db.yunfbzwdftdnclmdcjhh.supabase.co || true
          getent hosts db.yunfbzwdftdnclmdcjhh.supabase.co || true
          
      - name: Force IPv4 for Supabase DB
        shell: bash
        run: |
          set -euo pipefail
          H="db.yunfbzwdftdnclmdcjhh.supabase.co"

          IP=""

          # Try ahostsv4 (ignore failure so we can try fallbacks)
          IP="$(getent ahostsv4 "$H" 2>/dev/null | awk 'NR==1 {print $1}' || true)"

          # Fallback: getent hosts (filter IPv4 only)
          if [ -z "${IP:-}" ]; then
            IP="$(getent hosts "$H" 2>/dev/null | grep -m1 -E '^[0-9]+\.' | awk '{print $1}' || true)"
          fi

          # Fallback: dig (if present)
          if [ -z "${IP:-}" ] && command -v dig >/dev/null 2>&1; then
            IP="$(dig +short A "$H" | head -n1 || true)"
          fi

          if [ -z "${IP:-}" ]; then
            echo "No IPv4 found for $H" >&2
            exit 1
          fi

          echo "Resolved $H -> $IP"
         {
            echo "PG_SNI_HOST=$H"
            echo "PG_HOST_OVERRIDE=$IP"
          } >> "$GITHUB_ENV"

      - name: Write CA file
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p /tmp/certs
          echo "${{ secrets.SSL_CA_PEM }}" > /tmp/certs/supabase-root-2021.pem
          {
            echo "NODE_EXTRA_CA_CERTS=/tmp/certs/supabase-root-2021.pem"
            echo "SSL_CA_PEM_PATH=/tmp/certs/supabase-root-2021.pem"
          } >> "$GITHUB_ENV"
          
      - run: npm ci
      - name: db:status
        run: npm run db:status
