name: smoke
on:
  workflow_dispatch:
jobs:
  smoke:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      # ------------------------------
      # Block A – Node + CA setup
      # ------------------------------
      - name: Write CA file
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p /tmp/certs
          echo "${{ secrets.SSL_CA_PEM }}" > /tmp/certs/supabase-root-2021.pem
          {
            echo "NODE_EXTRA_CA_CERTS=/tmp/certs/supabase-root-2021.pem"
            echo "SSL_CA_PEM_PATH=/tmp/certs/supabase-root-2021.pem"
          } >> "$GITHUB_ENV"
      # ------------------------------
      # Block B – Try multiple connection strategies
      # ------------------------------
      - name: Try Supabase Connection Pooler
        shell: bash
        run: |
          set -euo pipefail
          
          DB_HOST="db.yunfbzwdftdnclmdcjhh.supabase.co"
          PROJECT_REF="yunfbzwdftdnclmdcjhh"
          
          echo "Trying connection pooler endpoints..."
          FOUND_IPV4="false"
          
          # Try endpoint 1
          POOLER="aws-0-us-east-1.pooler.supabase.com"
          echo "Checking $POOLER..."
          IP4="$(dig +short A "$POOLER" @8.8.8.8 | grep -E '^[0-9.]+$' | head -n1 || true)"
          if [ -n "${IP4}" ]; then
            echo "✓ Found IPv4 for pooler $POOLER: $IP4"
            echo "USE_POOLER=true" >> "$GITHUB_ENV"
            echo "POOLER_HOST=$POOLER" >> "$GITHUB_ENV"
            echo "POOLER_IP=$IP4" >> "$GITHUB_ENV"
            FOUND_IPV4="true"
          fi
          
          # Try endpoint 2 if not found
          if [ "$FOUND_IPV4" = "false" ]; then
            POOLER="aws-0-us-west-1.pooler.supabase.com
