name: Ingest Seed (manual)
on:
  workflow_dispatch: {}
concurrency:
  group: ingest-seed-${{ github.ref }}
  cancel-in-progress: true
jobs:
  seed:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
        working-directory: packages/ingest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: packages/ingest/package-lock.json
      - run: npm ci
      - name: Write CA file
      - name: Preflight (mask DSN, verify CA)
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
        run: |
          if (!(Test-Path C:\certs\supabase-root-2021.pem)) { throw "CA file missing" }
          Write-Host "CA first line:"; Get-Content C:\certs\supabase-root-2021.pem -TotalCount 1
          Write-Host "CA last line:";  Get-Content C:\certs\supabase-root-2021.pem -Tail 1
          node -e "const u=process.env.SUPABASE_DB_URL||''; console.log('DSN:', u.replace(/:\/\/([^:]+):([^@]+)@/,'://$1:***@'))"
      - name: db:seed
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
          SSL_CA_PEM_PATH: C:\certs\supabase-root-2021.pem
        run: node ./src/seed-smart.mjs
      - name: db:status
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
          SSL_CA_PEM_PATH: C:\certs\supabase-root-2021.pem
        run: node ./src/db-status.mjs
