name: Ingest Smoke (DB status)

on:
  workflow_dispatch:

jobs:
  smoke:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: npm
          cache-dependency-path: packages/ingest/package-lock.json

      - name: Install deps
        working-directory: packages/ingest
        run: npm ci

      - name: Write CA file
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path C:\certs | Out-Null
          Set-Content -Path C:\certs\supabase-root-2021.pem -Value "${{ secrets.SSL_CA_PEM }}"

      - name: db:status
        working-directory: packages/ingest
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
          SSL_CA_PEM_PATH: C:\certs\supabase-root-2021.pem
        run: npm run db:status
